// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtqJR3mvVnEeL8qZsGKdqouRy1DXAmSTA',
    appId: '1:1084692815857:web:c41c0d529c672fa18b2e50',
    messagingSenderId: '1084692815857',
    projectId: 'chat-frind-178d0',
    authDomain: 'chat-frind-178d0.firebaseapp.com',
    storageBucket: 'chat-frind-178d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGNdcD5lNb0EgzYkDZILx_aVdcS7iUkos',
    appId: '1:1084692815857:android:1a96e73460a7ba6c8b2e50',
    messagingSenderId: '1084692815857',
    projectId: 'chat-frind-178d0',
    storageBucket: 'chat-frind-178d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW46EkGsMT6MuAOiPhpQDIVPsNJp8tTts',
    appId: '1:1084692815857:ios:007cca3c4edb34b58b2e50',
    messagingSenderId: '1084692815857',
    projectId: 'chat-frind-178d0',
    storageBucket: 'chat-frind-178d0.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW46EkGsMT6MuAOiPhpQDIVPsNJp8tTts',
    appId: '1:1084692815857:ios:007cca3c4edb34b58b2e50',
    messagingSenderId: '1084692815857',
    projectId: 'chat-frind-178d0',
    storageBucket: 'chat-frind-178d0.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtqJR3mvVnEeL8qZsGKdqouRy1DXAmSTA',
    appId: '1:1084692815857:web:3d94f664d5b4181a8b2e50',
    messagingSenderId: '1084692815857',
    projectId: 'chat-frind-178d0',
    authDomain: 'chat-frind-178d0.firebaseapp.com',
    storageBucket: 'chat-frind-178d0.firebasestorage.app',
  );
}
